debug: false

# Number of blocks that the player can break at once.
max_tree_size: 256

# List of game mode where the player is can cut trees by breaking a single log.
# Default: SURVIVAL
enabled_gamemode:
  - SURVIVAL

# List of materials that are concidered as trees.
# Must be define as Material from Paper API: https://jd.papermc.io/paper/org/bukkit/Material.html. Regular expression is allowed.
# Example : ["ICE", ".*_LOG", "IRON_ORE"]
woods:
  - ".*_LOG"
  - ".*_WOOD"
  - "MANGROVE_ROOTS"

# List of tools that are concidered as breaking tree tools.
# Must be define as Material from Paper API: https://jd.papermc.io/paper/org/bukkit/Material.html. Regular expression is allowed.
# Example : ["ICE", ".*_LOG", "IRON_ORE"]
axes:
  - ".*_AXE"