debug: false

# Number of wood blocks that the player can break at once.
max_wood_blocks_falling: 256

# List of game mode where the player is can cut trees by breaking a single log.
# Default: SURVIVAL
enabled_gamemode:
  - SURVIVAL

# If true, the player will not be able to cut trees while sneaking.
sneaking_disable_tree_cut: true

# List of materials that are considered as tree trunks.
# Must be define as Material from Paper API: https://jd.papermc.io/paper/org/bukkit/Material.html. Regular expression is allowed.
# Example : ["ICE", ".*_LOG", "IRON_ORE"]
woods:
  - ".*_LOG"
  - ".*_WOOD"
  - "MANGROVE_ROOTS"

# List of tools that are considered as breaking tree tools.
# Must be define as Material from Paper API: https://jd.papermc.io/paper/org/bukkit/Material.html. Regular expression is allowed.
# Example : ["ICE", ".*_LOG", "IRON_ORE"]
axes:
  - ".*_AXE"


# Leaves ----------------------------------------------------------------------
# Leaves will only fall if connected to a wood block.

# If true, the leaves will fall with the tree.
leaves_falls: true

# Number of leaves blocks that the player can break at once.
max_leaves_blocks_falling: 256

# List of materials that are considered as tree leaves.
# Leaves only fall if not connected to a wood block that haven't been cut.
# Must be define as Material from Paper API: https://jd.papermc.io/paper/org/bukkit/Material.html. Regular expression is allowed.
# Example : ["ICE", ".*_LOG", "IRON_ORE"]
leaves:
  - ".*_LEAVES"
